### 1. Install Library

In [32]:
# %pip install pandas mysql-connector-python google-cloud-bigquery
# %pip install pandas-gbq

### 2. Import Library

In [33]:
import pandas as pd
import mysql.connector
import os
from pandas_gbq import to_gbq
from google.oauth2 import service_account
from google.cloud import bigquery
from dotenv import load_dotenv

### 3. Konfigurasi ke Database

In [34]:
# Load konfigurasi dari .env
load_dotenv()

# MySQL configurations
rds_host = os.getenv('RDS_HOST')
rds_dbname = os.getenv('RDS_DBNAME')
rds_user = os.getenv('RDS_USER')
rds_password = os.getenv('RDS_PASSWORD')

# Koneksi ke MySQL di Amazon RDS
conn_rds = mysql.connector.connect(
    host=rds_host,
    database=rds_dbname,
    user=rds_user,
    password=rds_password
)

### 4. Extract

#### 4.1 Extract semua tabel dan jadikan dataframe

In [35]:
# List of tables to extract
tables = [
    'destinations', 'categories', 'destination_facilities', 'facilities',
    'destination_addresses', 'provinces', 'cities', 'subdistricts', 'destination_media', 'admins'
]

# Function to load data from MySQL into pandas DataFrame
def load_table_to_df(table_name):
    query = f"SELECT * FROM {table_name}"
    df = pd.read_sql(query, conn_rds)
    return df

#### 4.2 Load semua tabel ke Dictionary

In [36]:
# Load all tables into individual DataFrames and store in a dictionary
dataframes = {}
for table in tables:
    df = load_table_to_df(table)
    dataframes[table] = df

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_26408\205905624.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn_rds)

#### 4.3 Close Connection

In [37]:
# Close the MySQL connection
conn_rds.close()

#### 4.4 Tampilkan Dataframe destinations

In [38]:
# Example of accessing and displaying a specific DataFrame
df_destinations = dataframes['destinations']
df_destinations

,id,category_id,name,description,open_time,close_time,entry_price,longitude,latitude,visit_count,created_at,updated_at,deleted_at
0,00319825-e81b-4a93-bf9a-eef836ccf6ce,eb77b590-b255-4ea1-b11a-d445a259ac62,Keraton Kasunanan Surakarta,Keraton Kasunanan Surakarta adalah istana resm...,9:00,14:00,20000.0,110.827903,-7.577736,278,2024-06-11 08:28:33,2024-06-14 04:55:48,None
1,005e32da-f5fb-405c-9772-f6424c011fac,eb77b590-b255-4ea1-b11a-d445a259ac62,Desa Wisata Kasongan,Desa yang terkenal dengan kerajinan gerabah da...,8:00,17:00,0.0,110.337978,-7.845291,243,2024-06-11 08:28:27,2024-06-13 13:00:10,None
2,01b8da3a-3987-4976-9ae7-46d6b8eacee5,eb77b590-b255-4ea1-b11a-d445a259ac62,Saung Angklung Udjo,Saung Angklung Udjo adalah pusat Seni dan Buda...,8:00,17:00,120000.0,107.654684,-6.897701,201,2024-06-11 08:28:33,2024-06-13 15:43:45,None
3,01ccaac9-97fe-42e1-8034-bc0c02471692,eb77b590-b255-4ea1-b11a-d445a259ac62,Museum Etnografi Sendawar,Museum Etnografi Sendawar merupakan museum per...,9:00,18:00,5000.0,115.701909,-0.232651,134,2024-06-11 08:28:20,2024-06-13 16:58:21,None
4,02834099-7ce7-44b9-8b27-e4db38f062bd,eb77b590-b255-4ea1-b11a-d445a259ac61,Danau Limboto,"Danau ini terletak di Kecamatan Limboto, tepat...",0:00,23:59,0.0,123.007543,0.577025,218,2024-06-11 08:28:21,2024-06-11 08:28:21,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,fbee819e-2b7b-44fe-8d5a-74dd345cea0e,eb77b590-b255-4ea1-b11a-d445a259ac61,Danau Tahai,Di kawasan objek wisata Danau Tahai ini terdap...,0:00,23:59,0.0,113.783202,-2.027312,136,2024-06-11 08:28:19,2024-06-11 08:28:19,None
318,fc780065-0848-467b-9625-9c24ecd2e9c2,eb77b590-b255-4ea1-b11a-d445a259ac61,Pantai Maaf,Pantai Maaf menawarkan perairan yang damai den...,6:00,18:00,10000.0,135.496749,-3.360245,163,2024-06-11 08:28:32,2024-06-11 08:28:32,None
319,fde8748a-2ec0-4211-89e5-12f3d63db81b,eb77b590-b255-4ea1-b11a-d445a259ac61,Piaynemo Raja Ampat,Piaynemo adalah salah satu ikon wisata di Raja...,10:00,17:00,150000.0,130.270813,-0.564206,123,2024-06-11 08:28:32,2024-06-11 08:28:32,None
320,fe1ebfe5-365f-4893-aa36-91e380bb2011,eb77b590-b255-4ea1-b11a-d445a259ac61,Wisata Pantai Gedo,Wisata Pantai Gedo adalah destinasi pantai ind...,6:00,18:00,15000.0,135.546550,-3.309413,299,2024-06-11 08:28:32,2024-06-11 08:28:32,None
321,ff779270-ee68-46cc-929c-cdd67d328772,eb77b590-b255-4ea1-b11a-d445a259ac61,Danau Emfote,Danau Emfote adalah salah satu destinasi alam ...,0:00,23:59,20000.0,140.539693,-2.660878,207,2024-06-11 08:28:30,2024-06-11 08:28:30,None

#### 4.5 Tampilkan Dataframe categories

In [39]:
df_categories = dataframes['categories']
df_categories

,id,name,url,created_at,updated_at,deleted_at
0,eb77b590-b255-4ea1-b11a-d445a259ac61,Alam,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
1,eb77b590-b255-4ea1-b11a-d445a259ac62,Seni dan Budaya,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
2,eb77b590-b255-4ea1-b11a-d445a259ac63,Sejarah,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None

#### 4.6 Tampilkan Dataframe destination_facilities

In [40]:
df_destination_facilities = dataframes['destination_facilities']
df_destination_facilities

,id,destination_id,facility_id,created_at,updated_at,deleted_at
0,00231d8c-fada-4fe2-b25f-6a7336097219,4388e724-d0b8-46e0-80bd-1362210b1cc1,19742db3-9121-4a6f-93dc-50cc051af77e,2024-06-13 18:48:11,2024-06-13 18:48:11,None
1,00462c88-5922-4a3f-bd75-1a9a0f6bd1f9,d6b4dcc6-e96e-4652-8587-52c2f5438f59,a5990fd0-6d85-4273-bb17-d912b688469c,2024-06-13 18:48:15,2024-06-13 18:48:15,None
2,008bf65a-397b-4499-a7fc-31f3177d82d0,ee06a47e-f264-40e9-b9c8-1a3a78492d84,56358ba0-3fad-43f7-9bf6-a7c86f2aec00,2024-06-13 18:48:14,2024-06-13 18:48:14,None
3,00a620f3-f277-4c9c-a369-399d6cc5aeb2,005e32da-f5fb-405c-9772-f6424c011fac,931e78bf-bb0d-4f47-9dfc-f550dcfa0763,2024-06-13 18:48:11,2024-06-13 18:48:11,None
4,00c9e0ef-c14e-4d95-8033-011506351ced,1982f523-8148-4e48-836e-72e9aa220f7c,1123257d-8bc0-4192-84fc-1bfb71d57d82,2024-06-13 18:48:16,2024-06-13 18:48:16,None
...,...,...,...,...,...,...
1362,ff2e258f-e402-4045-9f9c-5269c093b52d,7ca3cd71-4da0-4735-bfa3-cc2705419e6a,1123257d-8bc0-4192-84fc-1bfb71d57d82,2024-06-13 18:48:07,2024-06-13 18:48:07,None
1363,ff3c3e57-18aa-4b6b-90f0-5956a9118f06,b72c9d09-98dd-48ef-8dfd-03ab4a1b0d94,3fa4f5f1-e260-43f5-86cc-c876303235cf,2024-06-13 18:48:15,2024-06-13 18:48:15,None
1364,ff95ab6b-5cce-47bb-a656-a14eefa42800,4ce34993-985e-4e27-a31e-4753e6b8ef23,56358ba0-3fad-43f7-9bf6-a7c86f2aec00,2024-06-13 18:48:09,2024-06-13 18:48:09,None
1365,ffaf87e7-25b7-4a7b-b6c1-207dd9001bed,f79c2360-d2a8-4c61-aadf-d9966d76cd27,3fa4f5f1-e260-43f5-86cc-c876303235cf,2024-06-13 18:48:12,2024-06-13 18:48:12,None
1366,ffcda1ea-30c2-421b-8e39-1a40ba5f3499,963257de-d8bc-4bdd-92dd-3176fcf4ac4d,1123257d-8bc0-4192-84fc-1bfb71d57d82,2024-06-13 18:48:08,2024-06-13 18:48:08,None

#### 4.7 Tampilkan Dataframe facilities

In [41]:
df_facilities = dataframes['facilities']
df_facilities

,id,name,url,created_at,updated_at,deleted_at
0,1123257d-8bc0-4192-84fc-1bfb71d57d82,Tempat Sampah,https://storage.googleapis.com/provinces_url/f...,2024-06-13 18:48:05,2024-06-13 18:48:05,None
1,19742db3-9121-4a6f-93dc-50cc051af77e,Toko Oleh-oleh,https://storage.googleapis.com/provinces_url/f...,2024-06-13 18:48:05,2024-06-13 18:48:05,None
2,26668988-d77c-41b9-84ee-b954df8d7abf,Wahana Permainan,https://storage.googleapis.com/provinces_url/f...,2024-06-13 18:48:05,2024-06-13 18:48:05,None
3,3fa4f5f1-e260-43f5-86cc-c876303235cf,Toilet,https://storage.googleapis.com/provinces_url/f...,2024-06-13 18:48:05,2024-06-13 18:48:05,None
4,40c09801-cbe2-4451-b781-7c843148d647,Rumah Difabel,https://storage.googleapis.com/provinces_url/f...,2024-06-13 18:48:05,2024-06-13 18:48:05,None
5,56358ba0-3fad-43f7-9bf6-a7c86f2aec00,Pusat Informasi,https://storage.googleapis.com/provinces_url/f...,2024-06-13 18:48:05,2024-06-13 18:48:05,None
6,931e78bf-bb0d-4f47-9dfc-f550dcfa0763,Area Makanan,https://storage.googleapis.com/provinces_url/f...,2024-06-13 18:48:05,2024-06-13 18:48:05,None
7,a5990fd0-6d85-4273-bb17-d912b688469c,Area Parkir,https://storage.googleapis.com/provinces_url/f...,2024-06-13 18:48:05,2024-06-13 18:48:05,None
8,ca8f1e7e-887d-4eac-b93e-d5a4c098a04d,Tempat Ibadah,https://storage.googleapis.com/provinces_url/f...,2024-06-13 18:48:05,2024-06-13 18:48:05,None
9,e9ff877e-a324-441e-8175-53af5f0dc191,Penginapan,https://storage.googleapis.com/provinces_url/f...,2024-06-13 18:48:05,2024-06-13 18:48:05,None

#### 4.8 Tampilkan Dataframe destination_addresses

In [42]:
df_destination_addresses = dataframes['destination_addresses']
df_destination_addresses

,id,destination_id,province_id,city_id,subdistrict_id,street_name,postal_code,created_at,updated_at,deleted_at
0,011d2cae-f2bd-425f-8bce-8af97b9208c1,ce7170a6-7f38-42b8-8165-90303f381aee,64,6402,640206,Jl. Diponegoro No.26,75513,2024-06-11 08:28:20,2024-06-11 08:28:20,None
1,012d8602-cca7-47ec-9c60-b4e3b6ce9e63,be5a64df-c174-4829-b9c5-a01c82f78c15,34,3404,331001,"Jl. Raya Solo - Yogyakarta No. 16, Kranggan, B...",55571,2024-06-11 08:28:27,2024-06-11 08:28:27,None
2,02110a57-a844-4c11-af2e-5df5fe6cd36c,8aae7ff2-580b-42fe-958a-2b928ee54615,73,7302,320522,Jl. Tanah Toa,92574,2024-06-11 08:28:28,2024-06-11 08:28:28,None
3,028a7c9f-1649-4109-8416-aeab6ecf3b87,de220174-9f2d-42bf-b821-c02a510d215c,81,8101,110315,Jl. Istana Mini,97586,2024-06-11 08:28:30,2024-06-11 08:28:30,None
4,029b0550-2532-40ed-ae5f-80a6f0eddc3f,e3e7445e-6aec-4c84-8dea-ecd11476cb49,34,3471,347110,Jl. Margo Mulyo,55122,2024-06-11 08:28:27,2024-06-11 08:28:27,None
...,...,...,...,...,...,...,...,...,...,...
317,fcf1ce25-952f-4f47-b6bc-a1c9ae7701f8,c752381e-bf5e-48c7-b8f2-27a07959bee8,34,3471,347109,"Jl. Rotowijayan Blok No. 1, Panembahan",55131,2024-06-11 08:28:27,2024-06-11 08:28:27,None
318,fd7a687b-f7fc-482f-80ab-831b9306ab56,e7e9e5a3-b19f-41f7-b4f6-6b27f444303e,71,7171,717109,Jl. Ring Road Trans Sulawesi,95885,2024-06-11 08:28:21,2024-06-11 08:28:21,None
319,ffc60529-fe1f-498b-92e3-a0e274055aeb,f31d786b-61a9-447b-8827-07b384c03689,17,1701,177106,Jl. Pariwisata,38116,2024-06-11 08:28:25,2024-06-11 08:28:25,None
320,ffdb9337-4783-4db4-875d-dcf0f17392fc,35a8a9e5-f192-4228-94e6-93e58b94987b,74,7471,747104,Jl. Kebun Raya Nanga Nanga,93237,2024-06-11 08:28:29,2024-06-11 08:28:29,None
321,ffffb02d-f952-486a-837a-80c70cb184a1,b088cb7a-daab-4157-8299-4d74e34ff51d,16,1672,167201,Jl. Dempio Makmur,31581,2024-06-11 08:28:23,2024-06-11 08:28:23,None

#### 4.9 Tampilkan Dataframe provinces

In [43]:
df_provinces = dataframes['provinces']
df_provinces

,id,name,url,created_at,updated_at,deleted_at
0,11,Nanggroe Aceh Darussalam,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
1,12,SUMATERA UTARA,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
2,13,SUMATERA BARAT,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
3,14,RIAU,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
4,15,JAMBI,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
5,16,SUMATERA SELATAN,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
6,17,BENGKULU,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
7,18,LAMPUNG,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
8,19,BANGKA BELITUNG,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
9,21,KEPULAUAN RIAU,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
10,31,DKI JAKARTA,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
11,32,JAWA BARAT,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
12,33,JAWA TENGAH,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
13,34,DI YOGYAKARTA,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
14,35,JAWA TIMUR,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
15,36,BANTEN,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
16,51,BALI,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
17,52,NUSA TENGGARA BARAT,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
18,53,NUSA TENGGARA TIMUR,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
19,61,KALIMANTAN BARAT,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
20,62,KALIMANTAN TENGAH,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
21,63,KALIMANTAN SELATAN,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
22,64,KALIMANTAN TIMUR,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
23,65,KALIMANTAN UTARA,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
24,71,SULAWESI UTARA,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
25,72,SULAWESI TENGAH,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
26,73,SULAWESI SELATAN,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
27,74,SULAWESI TENGGARA,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
28,75,GORONTALO,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
29,76,SULAWESI BARAT,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
30,81,MALUKU,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
31,82,MALUKU UTARA,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
32,91,PAPUA,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
33,92,PAPUA BARAT,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
34,93,PAPUA SELATAN,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
35,94,PAPUA TENGAH,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
36,95,PAPUA PEGUNUNGAN,https://res.cloudinary.com/alta-minpro/image/u...,2024-06-11 08:27:47,2024-06-11 08:27:47,None
37,96,PAPUA BARAT DAYA,https://storage.googleapis.com/provinces_url/p...,2024-06-11 08:27:47,2024-06-11 08:27:47,None

#### 4.10 Tampilkan Dataframe cities

In [44]:
df_cities = dataframes['cities']
df_cities

,id,province_id,name,created_at,updated_at,deleted_at
0,1101,11,KAB. ACEH SELATAN,2024-06-11 08:27:47,2024-06-11 08:27:47,None
1,1102,11,KAB. ACEH TENGGARA,2024-06-11 08:27:47,2024-06-11 08:27:47,None
2,1103,11,KAB. ACEH TIMUR,2024-06-11 08:27:47,2024-06-11 08:27:47,None
3,1104,11,KAB. ACEH TENGAH,2024-06-11 08:27:47,2024-06-11 08:27:47,None
4,1105,11,KAB. ACEH BARAT,2024-06-11 08:27:47,2024-06-11 08:27:47,None
...,...,...,...,...,...,...
509,9504,95,KAB. TOLIKARA,2024-06-11 08:27:49,2024-06-11 08:27:49,None
510,9505,95,KAB. MAMBERAMO TENGAH,2024-06-11 08:27:49,2024-06-11 08:27:49,None
511,9506,95,KAB. YALIMO,2024-06-11 08:27:49,2024-06-11 08:27:49,None
512,9507,95,KAB. LANNY JAYA,2024-06-11 08:27:49,2024-06-11 08:27:49,None
513,9508,95,KAB. NDUGA,2024-06-11 08:27:49,2024-06-11 08:27:49,None

#### 4.11 Tampilkan Dataframe subdistricts

In [45]:
df_subdistricts = dataframes['subdistricts']
df_subdistricts

,id,city_id,name,created_at,updated_at,deleted_at
0,110101,1101,Bakongan,2024-06-11 08:27:49,2024-06-11 08:27:49,None
1,110102,1101,Kluet Utara,2024-06-11 08:27:49,2024-06-11 08:27:49,None
2,110103,1101,Kluet Selatan,2024-06-11 08:27:49,2024-06-11 08:27:49,None
3,110104,1101,Labuhanhaji,2024-06-11 08:27:49,2024-06-11 08:27:49,None
4,110105,1101,Meukek,2024-06-11 08:27:49,2024-06-11 08:27:49,None
...,...,...,...,...,...,...
7283,950839,9304,Yakapis,2024-06-11 08:28:17,2024-06-11 08:28:17,None
7284,950840,9171,Distrik Ebungfa,2024-06-11 08:28:14,2024-06-11 08:28:14,None
7285,950841,9171,Distrik Waibu,2024-06-11 08:28:14,2024-06-11 08:28:14,None
7286,950842,9501,Palebaga,2024-06-11 08:28:14,2024-06-11 08:28:14,None
7287,950843,9202,Distrik Manokwari,2024-06-11 08:28:14,2024-06-11 08:28:14,None

#### 4.12 Tampilkan Dataframe destination_media

In [46]:
df_destination_media = dataframes['destination_media']
df_destination_media

,id,destination_id,url,type,title,created_at,updated_at,deleted_at
0,00288a35-9e58-4fb5-8e1d-894c3e0ca43a,ee6c0ad0-fd22-46c2-96f2-178899751cd5,video.jpg,video,We Are Going On Bullrun 3,2024-06-11 08:28:29,2024-06-11 17:49:41,None
1,0046a99f-16a2-4086-b2df-b3d79048223c,73697664-ba03-4de1-ad47-13fa4f95abcd,https://storage.googleapis.com/provinces_url/v...,video,Mengagumi Arsitektur Unik Gedung Sate Bandung,2024-06-11 08:28:33,2024-06-11 08:28:33,None
2,005548a8-a773-4215-8144-b6feeb0eba4d,1c8539f7-a4c1-42b4-8e8e-4be2a16c1341,https://storage.googleapis.com/provinces_url/v...,video,Pesona Rumah Etnik Papua yang Memikat: Arsitek...,2024-06-11 08:28:32,2024-06-11 08:28:32,None
3,005f762b-2ff7-4f2f-8f3b-06d1a9ee449a,5ee3507b-78fa-405a-a6b3-c46d7a818a43,https://asset-2.tstatic.net/travel/foto/bank/i...,image,Serunya Liburan Keluarga di Taman Kyai Langgen...,2024-06-11 08:28:34,2024-06-11 08:28:34,None
4,0068439c-e80a-4b96-8b25-39ce71311af0,ba9a381d-0e78-4437-bd5c-0bce6c4a15fe,https://assets.promediateknologi.id/crop/0x0:0...,image,"Air Terjun Banangar, keindahan alam yang menye...",2024-06-11 08:28:18,2024-06-11 08:28:18,None
...,...,...,...,...,...,...,...,...
1921,ffa9ff93-32dd-413d-88fb-9f945f800f68,11ba8d8d-f4c1-4916-870f-30e3ce0dc050,https://assets.promediateknologi.id/crop/0x0:0...,image,Keindahan Pulau Kakara yang Mempesona: Pulau K...,2024-06-11 08:28:30,2024-06-11 08:28:30,None
1922,ffbc6ba5-8902-4625-9851-403a7dae707b,c04b5eb5-53cc-4692-9138-3647f598f8b8,https://gerbanglombok.co.id/wp-content/uploads...,image,Rasakan keajaiban alam Lombok dengan air terju...,2024-06-11 08:28:17,2024-06-11 08:28:17,None
1923,ffccc3c8-43d5-4244-9fff-533e3abdbf76,d2ef9e75-3443-4d7c-9188-04ce25e8d3fa,https://www.batiqa.com/upload/news/z/pekanbaru...,image,Menjelajahi Kemegahan Istana Siak Sri Indrapur...,2024-06-11 08:28:24,2024-06-11 08:28:24,None
1924,ffed9c82-d094-4e7d-9595-53fc66831e53,ee6c0ad0-fd22-46c2-96f2-178899751cd5,https://as2.ftcdn.net/v2/jpg/01/43/61/77/1000_...,image,Pesona Desa Wisata Sawai: Desa Wisata dengan K...,2024-06-11 08:28:29,2024-06-11 08:28:29,None
1925,fff78127-312b-4942-b29d-7f56b5666b06,f31d786b-61a9-447b-8827-07b384c03689,https://storage.googleapis.com/provinces_url/v...,video,Pantai Panjang: Destinasi Wisata Pantai Terind...,2024-06-11 08:28:25,2024-06-11 08:28:25,None

#### 4.13 Tampilkan Dataframe admins

In [47]:
df_admins = dataframes['admins']
df_admins

,id,username,password,profile_image_url,role,refresh_token,created_at,updated_at,deleted_at,delete_milli
0,0490e6e3-2cad-4483-9669-6eb8c3cdb3b6,username,$2a$10$GguFg4Rxqa8LELhfNFi70ekCQbc8qVkOSApftq2...,None,admin,,2024-06-08 10:28:28,2024-06-11 14:33:16,2024-06-11 14:33:15.525,1718116395523
1,06e02950-e61b-4e4a-83d2-5ccd474bdb67,adminke189,$2a$10$kooqc1wClsubh4kRahqvzumdIht4ASSJwQkVbMJ...,None,admin,,2024-06-11 07:12:49,2024-06-12 04:02:27,2024-06-12 04:02:26.631,1718164946629
2,0851c7bf-6303-4cc5-a035-114133eb7d97,adminke8,$2a$10$/Qi5GYmq0ApWD8qRZq.3CuG9rveekv4usOCQrH6...,None,admin,,2024-06-12 15:12:20,2024-06-12 15:13:56,2024-06-12 15:13:56.287,1718205236285
3,08f14449-27da-4ffc-a806-2605d14f0f28,adminke142,$2a$10$JuS0b688mIyjpsM965TnQueDyxpjBknYsoQYtSK...,None,admin,,2024-06-08 14:11:05,2024-06-12 14:39:04,2024-06-12 14:39:04.377,1718203144375
4,091b5b67-39fc-4dd1-8b37-9c53f0bb991e,adminke8,$2a$10$cXdiJii0a6XwaSek9ay1Y.T/RDrnfjR.IiwfyZl...,None,admin,,2024-06-12 15:26:44,2024-06-12 15:29:03,2024-06-12 15:29:02.839,1718206142838
5,0953fa2b-e639-4fad-8c6a-1c55b45fdfbe,adminke111,$2a$10$5YTJhep/SUTj7OY/bmELJuo.wPzZ3KVV/6RK/Mj...,None,admin,,2024-06-08 13:47:08,2024-06-12 10:00:23,2024-06-12 10:00:22.530,1718186422528
6,119b9d6f-ab2a-4e2a-8730-234df2c79913,adminke8,$2a$10$/SFKqNgQ1pcONyxwVRrx/ufnY5dIIBi/JCb3FiE...,None,admin,,2024-06-12 15:37:07,2024-06-12 15:48:14,2024-06-12 15:48:14.309,1718207294307
7,15a6f39f-197e-464c-8309-446e32fc0bcc,adminke3,$2a$10$dYf6qyzUe5KN8aywJtkuDeiPDJkJgmeluzq7Uq....,None,admin,,2024-06-08 10:27:03,2024-06-12 08:58:06,NaT,0
8,193cbe97-ccd2-42f3-b31c-76bed2c7ac61,adminku2,$2a$10$HLzVuiD8Lq.ojSfr89ZwAOBQVIJebRr22ZBrLd7...,None,admin,,2024-06-12 11:43:03,2024-06-12 14:39:30,2024-06-12 14:39:29.865,1718203169864
9,1996d11f-f991-4e41-8860-d84c24ef803b,adminke9,$2a$10$orRe0wAUnWIGcg9fZc0uYu4LqIhh6dX/6k147yI...,None,admin,,2024-06-12 14:52:38,2024-06-12 14:58:24,2024-06-12 14:58:23.979,1718204303977
10,20203894-bf75-4aa8-880a-f16c1427e0ac,adminke8,$2a$10$MqPO33EyTv6Y5cOJhEK5T.KEDN98n1vISBrM8Ud...,None,admin,,2024-06-12 14:58:46,2024-06-12 14:59:28,2024-06-12 14:59:28.398,1718204368397
11,2f37b189-159b-4797-82eb-394b3deddb4c,adminke21,$2a$10$Lb.I2tk4YTciAA.XcjA8KuCSFwJStTxHL3nYDkP...,None,admin,,2024-06-12 06:48:58,2024-06-12 14:39:13,2024-06-12 14:39:12.830,1718203152829
12,3b2a2f6d-a667-4cf3-9c24-c59b874d311b,iniadmin,$2a$10$vhh/IsXdGNtx00kBhcwtvOXjRYXmAoy5pIhJKq0...,None,admin,,2024-06-08 02:51:56,2024-06-14 08:06:02,NaT,0
13,3b8a7188-ef26-42bb-821c-587f5573b047,cobalagi,$2a$10$5fRY6/EaGFQmRiHgq5O24.yLY/emsKhN4n.cTv6...,None,admin,,2024-06-08 02:54:20,2024-06-12 10:35:32,NaT,0
14,49caf40a-f87c-4556-af59-0c5efa3e38f0,admin,$2a$10$H4BjeW/nBgxVWcUNaWBgoOsLHaRKOy7colnlCmk...,None,admin,eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6I...,2024-05-30 07:29:45,2024-06-14 08:18:24,NaT,0
15,4bfdef20-8f26-4a74-8214-b23cc64cd302,adminke4,$2a$10$qiL.tInH2nVkrxNfAfjVd.QI7nftfWYOvkXSWY4...,None,admin,,2024-06-08 10:27:30,2024-06-12 10:03:02,NaT,0
16,4dcb2f62-1314-44fb-91b2-68fc19681ef2,adminke20,$2a$10$s9Z4hfXTJRhTzDiKEXlaG.XVDkXTU56AlPmjgt5...,None,admin,,2024-06-12 06:02:49,2024-06-12 14:39:26,2024-06-12 14:39:26.177,1718203166175
17,4ebdfb3a-131d-4814-ad26-7da77a39effd,adminke19,$2a$10$nMf7gtOuip1v9YMEeP1uMOhajXnKTNDSMIMTLfP...,None,admin,,2024-06-12 05:59:36,2024-06-12 14:39:07,2024-06-12 14:39:07.171,1718203147169
18,5968ed78-12ec-4f15-a9bf-4a8569b2fff3,adminke9,$2a$10$YnukIlvbBzsbqHJ/mt/Oy.BU193tcs7ada.nmPQ...,None,admin,,2024-06-12 14:44:10,2024-06-12 14:45:48,2024-06-12 14:45:48.370,1718203548368
19,62514cb4-97db-4025-92ce-2afefcf67a96,adminke13,$2a$10$klVaiVK/AcMXcn5rf/Eslufwh72b39v6B3EGERS...,None,admin,,2024-06-08 13:53:56,2024-06-12 12:04:34,2024-06-12 12:04:34.338,1718193874336
20,6480a16f-637f-4602-a2ed-31eebc4594b2,adminke10,$2a$10$LQWiSB3YNndbVc8ZT/xHkeinnVMl.BxNQNp4iiI...,None,admin,,2024-06-08 13:43:19,2024-06-12 10:00:14,2024-06-12 10:00:14.120,1718186414118
21,66801733-815d-463c-9150-acf89a7b7894,adminke10,$2a$10$z0ZoXG5r2TlXdOjQ49oKZ.77yIeqrNQdYMwD6lW...,None,admin,,2024-06-12 14:56:12,2024-06-12 14:58:29,2024-06-12 14:58:28.717,1718204308715
22,68bef306-df14-4489-9b88-533b41a7b523,adminke8,$2a$10$c6U1XSFBgJSfo064KWeNbeKX.zECXLMtOgsk8XB...,None,admin,,2024-06-12 15:29:29,2024-06-12 15:36:42,2024-06-12 15:36:42.059,1718206602057
23,6cb76628-5461-4eb1-8a8d-99b351a78862,adminke178,$2a$10$nIozd5skx0UG9THcziE3K.qSvEUIf94SZ1VWv/W...,None,admin,,2024-06-11 07:10:34,2024-06-12 04:02:30,2024-06-12 04:02:29.971,1718164949969
24,7dad37a7-9c99-4893-a3f5-ef31d6612073,adminku3,$2a$10$KyV1lpP2t9/oXCdZ25yex.0SBx/qE9fzU1zGgzy...,None,admin,,2024-06-12 11:44:13,2024-06-12 14:39:41,2024-06-12 14:39:41.204,1718203181202
25,7de1c174-dc85-4994-98c3-68518ac00679,hallopanda1234,$2a$10$BVmXiLvgGPAeohvbB8VpqeSAD6w4yFuR5CQbE40...,https://res.cloudinary.com/alta-minpro/image/u...,admin,,2024-06-12 11:54:48,2024-06-12 14:39:38,2024-06-12 14:39:37.569,1718203177566
26,8331f6ee-8ae8-4793-921b-922a3dc6db74,halopanda123,$2a$10$bNmC88ZrYtaUbCydObtlOeM90JLJmvSBtSoomSz...,https://res.cloudinary.com/alta-minpro/image/u...,admin,,2024-06-08 02:50:16,2024-06-13 08:10:51,NaT,0
27,835d08c4-caa8-454a-9e81-699a11d07d60,adminke2,$2a$10$2e6g//IW9nJsdNZMD7Hx8ekUI/sxtSJJD6QVJ7s...,None,admin,,2024-06-08 10:26:42,2024-06-12 10:00:51,NaT,0
28,86da39a1-051e-4c6c-98ad-55584e6f216d,adminke5,$2a$10$RoMDdwOLGgSk.p9ndDgel.ROpM7iqNXfA8kYHOz...,https://res.cloudinary.com/alta-minpro/image/u...,admin,eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6I...,2024-06-08 10:27:58,2024-06-13 14:28:27,NaT,0
29,99116a17-b358-4889-a304-0e94c8b7ae46,adminke21,$2a$10$LzP0mLOQTRONDZQ.MNy.F.j7QA22Q7J.gBFXkLG...,None,admin,,2024-06-12 06:48:01,2024-06-12 06:48:36,2024-06-12 06:48:36.273,1718174916272
30,9e23d978-4e5a-4b8a-b47b-5ff29bfcf386,adminke30,$2a$10$wLBeFLo0j6f3yLj9Rya.UOjS3Ac2NCususr6zqC...,None,admin,,2024-06-08 10:28:53,2024-06-12 09:34:13,2024-06-12 09:34:13.177,1718184853175
31,a0860d0e-dfa1-4d85-906d-9e9acfd61889,adminku1,$2a$10$KqExOU63fhOeacNzIVgDsu0lt/5R/q79vtGnPYG...,None,admin,,2024-06-12 11:41:35,2024-06-12 14:39:23,2024-06-12 14:39:23.151,1718203163150
32,a9bbb56f-080b-40ca-9a65-9e0b401945e4,adminke8,$2a$10$cBtHH6kyLGdSlC9z0KIJDunmL23G.ayJVfu/5PP...,None,admin,,2024-06-12 15:21:09,2024-06-12 15:22:03,2024-06-12 15:22:03.325,1718205723323
33,ab9aebda-f020-413b-8eea-f7e00840e2a6,adminke8,$2a$10$ehlK.llf9upPC/lOmMdYuOnHunXYRs9bb9c0pM9...,None,admin,,2024-06-12 14:46:08,2024-06-12 14:53:40,2024-06-12 14:53:39.858,1718204019856
34,ae1839c8-b7ab-4754-9200-f2e081bb1eeb,adminke7,$2a$10$lQTut9JGQg62R4QbqFJ1teg160ByRR92h8JoQJb...,https://res.cloudinary.com/alta-minpro/image/u...,admin,,2024-06-12 14:40:02,2024-06-13 06:52:59,NaT,0
35,b8c5924d-fa1b-425e-956b-e295d359b96c,cobalagi2,$2a$10$uxekfgSQ4stZKH9ZzFCaYe5uEDFWA3GDMiWm9tt...,https://res.cloudinary.com/alta-minpro/image/u...,admin,,2024-06-08 02:55:11,2024-06-08 10:23:06,2024-06-08 10:23:06.295,1717842186293
36,ba18f772-339f-49c0-acb5-0d97b4513581,adminke88,$2a$10$.ncpzHQDTJzuhLv1b0.eDeTT5/NBYHS0udIVUMC...,None,admin,,2024-06-08 12:58:49,2024-06-12 09:34:09,2024-06-12 09:34:09.191,1718184849189
37,bb0ea519-6181-4523-934e-fa1c51e98c11,adminke21,$2a$10$P9N72QanY2D8mhTZEPbXzO.snrw.qI8Oe6Vqjly...,None,admin,,2024-06-12 06:46:45,2024-06-12 06:47:40,2024-06-12 06:47:40.229,1718174860227
38,c9695b5a-dcb8-4115-a4be-02e1359c304c,adminke8,$2a$10$ycu5ENxBSjDE.SLk7VF0yeiQFLObx9wxKoYksoT...,None,admin,eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6I...,2024-06-12 10:39:40,2024-06-12 14:39:19,2024-06-12 14:39:19.343,1718203159341
39,ccd89953-cea7-409c-aef2-2644c3d3a01c,cobalagi3,$2a$10$lArALrE8580JQ5IVPuB/KuGP2EIeMpaOEc0qmwV...,https://res.cloudinary.com/alta-minpro/image/u...,admin,,2024-06-08 03:25:09,2024-06-08 10:22:34,2024-06-08 10:22:34.218,1717842154216
40,d6453a56-d236-4661-b5a5-ce7e74d79e12,adminke99,$2a$10$Ep/MALOfYwSmRjpUtxm/HenWdWKssPHodUoUzLc...,None,admin,eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6I...,2024-06-08 12:59:23,2024-06-12 14:39:10,2024-06-12 14:39:09.772,1718203149769
41,d751ca08-98b9-47d7-8af6-998da7ce168d,adminke1,$2a$10$CZfHH./it6u2Fowz1/MWCunOLH/U2KZRuYuN6i/...,https://res.cloudinary.com/alta-minpro/image/u...,admin,,2024-06-08 10:26:18,2024-06-11 14:44:14,2024-06-11 14:44:13.936,1718117053934
42,d8cdde76-d6b8-4015-95ff-4845172cf66d,adminke13,$2a$10$FbfBB2EcvwPI3liZBi1NeOq3cQpGIqHFnGH1QMC...,https://res.cloudinary.com/alta-minpro/image/u...,admin,,2024-06-08 13:51:45,2024-06-08 13:53:19,2024-06-08 13:53:18.886,1717854798884
43,dc85d238-c134-4f71-9323-0df39d96b1b3,hallopanda123,$2a$10$BBuCMcix5BUFZKuEWRXhFOm8YMpNAQmUtTxJGwO...,None,admin,,2024-06-12 11:51:51,2024-06-12 14:39:33,2024-06-12 14:39:33.041,1718203173039
44,dc98b994-6d3d-4695-8743-ba8b29031619,amanda,$2a$10$5QXv9Mczcfuehomh78t5Vex5l4J1iY09ioT4NDb...,None,admin,,2024-06-12 08:47:41,2024-06-12 14:39:16,2024-06-12 14:39:16.363,1718203156361
45,dd3bcc77-3b2f-45a2-8202-a78feaeba9e1,amanda,$2a$10$8Nq7tCX1fA8Xy/Y0YayFOerKWxF7usRc3o2b.ys...,None,admin,,2024-06-14 08:05:30,2024-06-14 08:07:01,2024-06-14 08:07:00.741,1718352420739
46,def6e858-1a50-41a3-9451-a49f86677d12,adminke158,$2a$10$KX6mdbBkl5dd6dX7ba7/1OOzAUkV7k2BC9ksq8D...,None,admin,,2024-06-08 14:11:39,2024-06-12 04:02:33,2024-06-12 04:02:33.180,1718164953178
47,e553d1ab-9b92-4425-a357-b7ed49801f13,superadmin,$2a$10$SLWFHkb5TeDa7b58TyTteex0FBBKpI/kFUT4MJy...,None,super admin,eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6I...,2024-05-30 07:26:11,2024-06-14 08:14:35,NaT,0
48,ecfed68b-39b4-4ffb-af22-17e1fc92b352,adminke8,$2a$10$1DXBnY15h0SushePYrYV9edZa1kh150xsH009gH...,None,admin,,2024-06-12 15:14:13,2024-06-12 15:18:04,2024-06-12 15:18:03.910,1718205483908
49,ed479c52-ee84-4a95-a8dc-b1866895552b,adminke8,$2a$10$aBiCWwnnj.C2ZHQqt94t7eCUQi80BkwyTzfxjKb...,None,admin,,2024-06-12 15:05:35,2024-06-12 15:06:58,2024-06-12 15:06:57.538,1718204817536
50,f271cfd8-0413-4afb-8f62-f34671a3097c,adminke21,$2a$10$ryq4AoD5NfXDaxYtylk9GuqhjravyTBYHKkWAcs...,None,admin,,2024-06-12 06:45:50,2024-06-12 06:46:16,2024-06-12 06:46:16.157,1718174776156

### 5. Transformation

#### 5.1 Merged df_destination_facilities dan df_facilities

In [48]:
# Menggabungkan DataFrame
df_merged_facilities = pd.merge(df_destination_facilities, df_facilities, left_on='facility_id', right_on='id')

# Memilih kolom yang diinginkan dari df_facilities
df_dim_facilities = df_merged_facilities[['facility_id', 'name', 'url']].drop_duplicates()
df_dim_facilities.rename(columns={'facility_id': 'id'}, inplace=True)

# Mengurutkan index kembali
df_dim_facilities.reset_index(drop=True, inplace=True)

##### 5.1.1 Dim Facilities

In [49]:
# Menampilkan DataFrame hasil
df_dim_facilities

,id,name,url
0,19742db3-9121-4a6f-93dc-50cc051af77e,Toko Oleh-oleh,https://storage.googleapis.com/provinces_url/f...
1,a5990fd0-6d85-4273-bb17-d912b688469c,Area Parkir,https://storage.googleapis.com/provinces_url/f...
2,56358ba0-3fad-43f7-9bf6-a7c86f2aec00,Pusat Informasi,https://storage.googleapis.com/provinces_url/f...
3,931e78bf-bb0d-4f47-9dfc-f550dcfa0763,Area Makanan,https://storage.googleapis.com/provinces_url/f...
4,1123257d-8bc0-4192-84fc-1bfb71d57d82,Tempat Sampah,https://storage.googleapis.com/provinces_url/f...
5,3fa4f5f1-e260-43f5-86cc-c876303235cf,Toilet,https://storage.googleapis.com/provinces_url/f...
6,ca8f1e7e-887d-4eac-b93e-d5a4c098a04d,Tempat Ibadah,https://storage.googleapis.com/provinces_url/f...
7,e9ff877e-a324-441e-8175-53af5f0dc191,Penginapan,https://storage.googleapis.com/provinces_url/f...
8,26668988-d77c-41b9-84ee-b954df8d7abf,Wahana Permainan,https://storage.googleapis.com/provinces_url/f...
9,40c09801-cbe2-4451-b781-7c843148d647,Rumah Difabel,https://storage.googleapis.com/provinces_url/f...

#### 5.2 Merged df_destination_addresses dengan df_provinces, df_cities, df_subdistricts

In [50]:
# Gabungkan DataFrame
df_merged_address = pd.merge(df_destination_addresses, df_provinces, left_on='province_id', right_on='id', suffixes=('_dest', '_prov'))
df_merged_address = pd.merge(df_merged_address, df_cities, left_on='city_id', right_on='id', suffixes=('_prov', '_city'))
df_merged_address = pd.merge(df_merged_address, df_subdistricts, left_on='subdistrict_id', right_on='id', suffixes=('_city', '_subd'))

# Pilih kolom yang diinginkan
df_dim_address = df_merged_address[['id_dest', 'name_prov', 'name_city', 'name', 'street_name', 'postal_code']]

# Ubah nama kolom
df_dim_address.columns = ['id', 'provinces', 'cities', 'subdistricts', 'street_name', 'postal_code']

##### 5.2.1 Dim Address

In [51]:
# Tampilkan DataFrame hasil
df_dim_address

,id,provinces,cities,subdistricts,street_name,postal_code
0,011d2cae-f2bd-425f-8bce-8af97b9208c1,KALIMANTAN TIMUR,KAB. KUTAI KARTANEGARA,Tenggarong,Jl. Diponegoro No.26,75513
1,e3d168e4-f92a-449f-af5c-a7af23305a69,KALIMANTAN TIMUR,KAB. KUTAI KARTANEGARA,Tenggarong,Jl. Panji,75513
2,cec8c58b-4918-48d3-8897-bd01593f46b4,KALIMANTAN TIMUR,KAB. KUTAI KARTANEGARA,Samboja,Jl. Bukit Merdeka,75271
3,25244f03-3a67-4da1-9d81-c7a7150e2109,KALIMANTAN TIMUR,KAB. BERAU,Batu Putih,Jl. Desa Tulung Ni'Lenggo,77372
4,5f160160-402b-4956-8667-eadbdaafc370,KALIMANTAN TIMUR,KAB. BERAU,Biduk-Biduk,Jl. Labuan Kelambu,77373
...,...,...,...,...,...,...
317,fd7a687b-f7fc-482f-80ab-831b9306ab56,SULAWESI UTARA,KOTA MANADO,Malalayang,Jl. Ring Road Trans Sulawesi,95885
318,cf1f3fbd-22a2-46c6-91d7-7e8c51ebab35,BANGKA BELITUNG,KAB. BANGKA SELATAN,Toboali,Jl. Tanjung Ketapang,33783
319,d19d64db-7254-45fc-98c3-321a416556b5,BANGKA BELITUNG,KAB. BELITUNG,Tanjung Pandan,Jl. Gajah Mada,33411
320,d9d0f944-5be4-4850-a6c2-1bbe402f02ec,BANGKA BELITUNG,KAB. BANGKA,Sinar Baru,Jl. Laut,33211
321,da109565-09ed-45ba-9cc9-7ba5e8d5da4a,BANGKA BELITUNG,KAB. BANGKA TENGAH,Koba,Jl. Raya Toboali,33782

#### 5.3 Drop Column di df_destinations (Dim Destinations)

In [52]:
# Menghapus kolom-kolom yang tidak diinginkan
columns_to_drop = ['category_id', 'created_at', 'updated_at', 'deleted_at']
df_dim_destinations = df_destinations.drop(columns=columns_to_drop)

# Tampilkan hasil
df_dim_destinations

,id,name,description,open_time,close_time,entry_price,longitude,latitude,visit_count
0,00319825-e81b-4a93-bf9a-eef836ccf6ce,Keraton Kasunanan Surakarta,Keraton Kasunanan Surakarta adalah istana resm...,9:00,14:00,20000.0,110.827903,-7.577736,278
1,005e32da-f5fb-405c-9772-f6424c011fac,Desa Wisata Kasongan,Desa yang terkenal dengan kerajinan gerabah da...,8:00,17:00,0.0,110.337978,-7.845291,243
2,01b8da3a-3987-4976-9ae7-46d6b8eacee5,Saung Angklung Udjo,Saung Angklung Udjo adalah pusat Seni dan Buda...,8:00,17:00,120000.0,107.654684,-6.897701,201
3,01ccaac9-97fe-42e1-8034-bc0c02471692,Museum Etnografi Sendawar,Museum Etnografi Sendawar merupakan museum per...,9:00,18:00,5000.0,115.701909,-0.232651,134
4,02834099-7ce7-44b9-8b27-e4db38f062bd,Danau Limboto,"Danau ini terletak di Kecamatan Limboto, tepat...",0:00,23:59,0.0,123.007543,0.577025,218
...,...,...,...,...,...,...,...,...,...
317,fbee819e-2b7b-44fe-8d5a-74dd345cea0e,Danau Tahai,Di kawasan objek wisata Danau Tahai ini terdap...,0:00,23:59,0.0,113.783202,-2.027312,136
318,fc780065-0848-467b-9625-9c24ecd2e9c2,Pantai Maaf,Pantai Maaf menawarkan perairan yang damai den...,6:00,18:00,10000.0,135.496749,-3.360245,163
319,fde8748a-2ec0-4211-89e5-12f3d63db81b,Piaynemo Raja Ampat,Piaynemo adalah salah satu ikon wisata di Raja...,10:00,17:00,150000.0,130.270813,-0.564206,123
320,fe1ebfe5-365f-4893-aa36-91e380bb2011,Wisata Pantai Gedo,Wisata Pantai Gedo adalah destinasi pantai ind...,6:00,18:00,15000.0,135.546550,-3.309413,299
321,ff779270-ee68-46cc-929c-cdd67d328772,Danau Emfote,Danau Emfote adalah salah satu destinasi alam ...,0:00,23:59,20000.0,140.539693,-2.660878,207

#### 5.4 Drop Column di df_categories (Dim Categories)

In [53]:
# Menghapus kolom-kolom yang tidak diinginkan
columns_to_drop = ['url', 'created_at', 'updated_at', 'deleted_at']
df_dim_categories = df_categories.drop(columns=columns_to_drop)

# Tampilkan DataFrame setelah penghapusan kolom
df_dim_categories

                                     id             name
0  eb77b590-b255-4ea1-b11a-d445a259ac61             Alam
1  eb77b590-b255-4ea1-b11a-d445a259ac62  Seni dan Budaya
2  eb77b590-b255-4ea1-b11a-d445a259ac63          Sejarah

#### 5.5 Drop Column di df_destination_media (Dim Medias)

In [54]:
# Menghapus kolom-kolom yang tidak diinginkan
columns_to_drop = ['destination_id', 'created_at', 'updated_at', 'deleted_at']
df_dim_medias = df_destination_media.drop(columns=columns_to_drop)

# Tampilkan DataFrame setelah penghapusan kolom
df_dim_medias

,id,url,type,title
0,00288a35-9e58-4fb5-8e1d-894c3e0ca43a,video.jpg,video,We Are Going On Bullrun 3
1,0046a99f-16a2-4086-b2df-b3d79048223c,https://storage.googleapis.com/provinces_url/v...,video,Mengagumi Arsitektur Unik Gedung Sate Bandung
2,005548a8-a773-4215-8144-b6feeb0eba4d,https://storage.googleapis.com/provinces_url/v...,video,Pesona Rumah Etnik Papua yang Memikat: Arsitek...
3,005f762b-2ff7-4f2f-8f3b-06d1a9ee449a,https://asset-2.tstatic.net/travel/foto/bank/i...,image,Serunya Liburan Keluarga di Taman Kyai Langgen...
4,0068439c-e80a-4b96-8b25-39ce71311af0,https://assets.promediateknologi.id/crop/0x0:0...,image,"Air Terjun Banangar, keindahan alam yang menye..."
...,...,...,...,...
1921,ffa9ff93-32dd-413d-88fb-9f945f800f68,https://assets.promediateknologi.id/crop/0x0:0...,image,Keindahan Pulau Kakara yang Mempesona: Pulau K...
1922,ffbc6ba5-8902-4625-9851-403a7dae707b,https://gerbanglombok.co.id/wp-content/uploads...,image,Rasakan keajaiban alam Lombok dengan air terju...
1923,ffccc3c8-43d5-4244-9fff-533e3abdbf76,https://www.batiqa.com/upload/news/z/pekanbaru...,image,Menjelajahi Kemegahan Istana Siak Sri Indrapur...
1924,ffed9c82-d094-4e7d-9595-53fc66831e53,https://as2.ftcdn.net/v2/jpg/01/43/61/77/1000_...,image,Pesona Desa Wisata Sawai: Desa Wisata dengan K...
1925,fff78127-312b-4942-b29d-7f56b5666b06,https://storage.googleapis.com/provinces_url/v...,video,Pantai Panjang: Destinasi Wisata Pantai Terind...

#### 5.6 Merged for Fact Table (destination_fact)

In [55]:
# Merge dataframes
merged_df = pd.merge(df_destinations, df_categories, left_on='category_id', right_on='id', suffixes=('_destinations', '_categories'))
merged_df = pd.merge(merged_df, df_destination_media, left_on='id_destinations', right_on='destination_id')
merged_df = pd.merge(merged_df, df_destination_facilities, left_on='id_destinations', right_on='destination_id', how='left')
merged_df = pd.merge(merged_df, df_destination_addresses, left_on='id_destinations', right_on='destination_id', how='left')

merged_df

,id_destinations,category_id,name_destinations,description,open_time,close_time,entry_price,longitude,latitude,visit_count,...,id,destination_id,province_id,city_id,subdistrict_id,street_name,postal_code,created_at,updated_at,deleted_at
0,00319825-e81b-4a93-bf9a-eef836ccf6ce,eb77b590-b255-4ea1-b11a-d445a259ac62,Keraton Kasunanan Surakarta,Keraton Kasunanan Surakarta adalah istana resm...,9:00,14:00,20000.0,110.827903,-7.577736,278,...,f9eefd7d-3af2-44c8-ae2e-135fefa6205c,00319825-e81b-4a93-bf9a-eef836ccf6ce,33,3372,337203,Jl. Kamandungan,57144,2024-06-11 08:28:33,2024-06-11 08:28:33,None
1,00319825-e81b-4a93-bf9a-eef836ccf6ce,eb77b590-b255-4ea1-b11a-d445a259ac62,Keraton Kasunanan Surakarta,Keraton Kasunanan Surakarta adalah istana resm...,9:00,14:00,20000.0,110.827903,-7.577736,278,...,f9eefd7d-3af2-44c8-ae2e-135fefa6205c,00319825-e81b-4a93-bf9a-eef836ccf6ce,33,3372,337203,Jl. Kamandungan,57144,2024-06-11 08:28:33,2024-06-11 08:28:33,None
2,00319825-e81b-4a93-bf9a-eef836ccf6ce,eb77b590-b255-4ea1-b11a-d445a259ac62,Keraton Kasunanan Surakarta,Keraton Kasunanan Surakarta adalah istana resm...,9:00,14:00,20000.0,110.827903,-7.577736,278,...,f9eefd7d-3af2-44c8-ae2e-135fefa6205c,00319825-e81b-4a93-bf9a-eef836ccf6ce,33,3372,337203,Jl. Kamandungan,57144,2024-06-11 08:28:33,2024-06-11 08:28:33,None
3,00319825-e81b-4a93-bf9a-eef836ccf6ce,eb77b590-b255-4ea1-b11a-d445a259ac62,Keraton Kasunanan Surakarta,Keraton Kasunanan Surakarta adalah istana resm...,9:00,14:00,20000.0,110.827903,-7.577736,278,...,f9eefd7d-3af2-44c8-ae2e-135fefa6205c,00319825-e81b-4a93-bf9a-eef836ccf6ce,33,3372,337203,Jl. Kamandungan,57144,2024-06-11 08:28:33,2024-06-11 08:28:33,None
4,00319825-e81b-4a93-bf9a-eef836ccf6ce,eb77b590-b255-4ea1-b11a-d445a259ac62,Keraton Kasunanan Surakarta,Keraton Kasunanan Surakarta adalah istana resm...,9:00,14:00,20000.0,110.827903,-7.577736,278,...,f9eefd7d-3af2-44c8-ae2e-135fefa6205c,00319825-e81b-4a93-bf9a-eef836ccf6ce,33,3372,337203,Jl. Kamandungan,57144,2024-06-11 08:28:33,2024-06-11 08:28:33,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8170,f7f737d5-e116-4786-bb7a-4fbc97b35d2f,eb77b590-b255-4ea1-b11a-d445a259ac63,Masjid Menara Kudus,Masjid Menara Kudus adalah masjid bersejarah y...,0:00,23:59,0.0,110.832831,-6.804204,199,...,360b4f70-e498-4bcf-ab03-4dc87208aa50,f7f737d5-e116-4786-bb7a-4fbc97b35d2f,33,3319,331902,Jl. Menara,59315,2024-06-11 08:28:34,2024-06-11 08:28:34,None
8171,f7f737d5-e116-4786-bb7a-4fbc97b35d2f,eb77b590-b255-4ea1-b11a-d445a259ac63,Masjid Menara Kudus,Masjid Menara Kudus adalah masjid bersejarah y...,0:00,23:59,0.0,110.832831,-6.804204,199,...,360b4f70-e498-4bcf-ab03-4dc87208aa50,f7f737d5-e116-4786-bb7a-4fbc97b35d2f,33,3319,331902,Jl. Menara,59315,2024-06-11 08:28:34,2024-06-11 08:28:34,None
8172,f7f737d5-e116-4786-bb7a-4fbc97b35d2f,eb77b590-b255-4ea1-b11a-d445a259ac63,Masjid Menara Kudus,Masjid Menara Kudus adalah masjid bersejarah y...,0:00,23:59,0.0,110.832831,-6.804204,199,...,360b4f70-e498-4bcf-ab03-4dc87208aa50,f7f737d5-e116-4786-bb7a-4fbc97b35d2f,33,3319,331902,Jl. Menara,59315,2024-06-11 08:28:34,2024-06-11 08:28:34,None
8173,f7f737d5-e116-4786-bb7a-4fbc97b35d2f,eb77b590-b255-4ea1-b11a-d445a259ac63,Masjid Menara Kudus,Masjid Menara Kudus adalah masjid bersejarah y...,0:00,23:59,0.0,110.832831,-6.804204,199,...,360b4f70-e498-4bcf-ab03-4dc87208aa50,f7f737d5-e116-4786-bb7a-4fbc97b35d2f,33,3319,331902,Jl. Menara,59315,2024-06-11 08:28:34,2024-06-11 08:28:34,None
8174,f7f737d5-e116-4786-bb7a-4fbc97b35d2f,eb77b590-b255-4ea1-b11a-d445a259ac63,Masjid Menara Kudus,Masjid Menara Kudus adalah masjid bersejarah y...,0:00,23:59,0.0,110.832831,-6.804204,199,...,360b4f70-e498-4bcf-ab03-4dc87208aa50,f7f737d5-e116-4786-bb7a-4fbc97b35d2f,33,3319,331902,Jl. Menara,59315,2024-06-11 08:28:34,2024-06-11 08:28:34,None

In [56]:
print(merged_df.columns)

Index(['id_destinations', 'category_id', 'name_destinations', 'description',
       'open_time', 'close_time', 'entry_price', 'longitude', 'latitude',
       'visit_count', 'created_at_destinations', 'updated_at_destinations',
       'deleted_at_destinations', 'id_categories', 'name_categories', 'url_x',
       'created_at_categories', 'updated_at_categories',
       'deleted_at_categories', 'id_x', 'destination_id_x', 'url_y', 'type',
       'title', 'created_at_x', 'updated_at_x', 'deleted_at_x', 'id_y',
       'destination_id_y', 'facility_id', 'created_at_y', 'updated_at_y',
       'deleted_at_y', 'id', 'destination_id', 'province_id', 'city_id',
       'subdistrict_id', 'street_name', 'postal_code', 'created_at',
       'updated_at', 'deleted_at'],
      dtype='object')

#### 5.7 Merged for Fact Table

In [57]:
# Calculate additional columns
merged_df['total_content_video'] = (merged_df['type'] == 'video').astype(int)
merged_df['total_pendapatan'] = merged_df['entry_price'] * merged_df['visit_count']

# Select relevant columns for fact table
df_destination_fact = merged_df[['id_destinations', 'category_id', 'id_x', 'facility_id', 'id', 'total_content_video', 'total_pendapatan']]

# Rename columns
df_destination_fact.columns = ['destinations_id', 'categories_id', 'medias_id', 'facilities_id', 'address_id', 'total_content_video', 'total_pendapatan']

# Drop duplicates
df_destination_fact = df_destination_fact.drop_duplicates()

# Sort by destination_id
df_destination_fact = df_destination_fact.sort_values(by='destinations_id')

# Reset index to make it sequential
df_destination_fact = df_destination_fact.reset_index(drop=True)

# Preview the result
df_destination_fact

,destinations_id,categories_id,medias_id,facilities_id,address_id,total_content_video,total_pendapatan
0,00319825-e81b-4a93-bf9a-eef836ccf6ce,eb77b590-b255-4ea1-b11a-d445a259ac62,24ca36a8-d037-46a3-9d41-06f86e91aed7,56358ba0-3fad-43f7-9bf6-a7c86f2aec00,f9eefd7d-3af2-44c8-ae2e-135fefa6205c,1,5560000.0
1,00319825-e81b-4a93-bf9a-eef836ccf6ce,eb77b590-b255-4ea1-b11a-d445a259ac62,f22dec50-95c5-42ea-ab87-e1a3e9b21811,a5990fd0-6d85-4273-bb17-d912b688469c,f9eefd7d-3af2-44c8-ae2e-135fefa6205c,0,5560000.0
2,00319825-e81b-4a93-bf9a-eef836ccf6ce,eb77b590-b255-4ea1-b11a-d445a259ac62,f22dec50-95c5-42ea-ab87-e1a3e9b21811,19742db3-9121-4a6f-93dc-50cc051af77e,f9eefd7d-3af2-44c8-ae2e-135fefa6205c,0,5560000.0
3,00319825-e81b-4a93-bf9a-eef836ccf6ce,eb77b590-b255-4ea1-b11a-d445a259ac62,f22dec50-95c5-42ea-ab87-e1a3e9b21811,56358ba0-3fad-43f7-9bf6-a7c86f2aec00,f9eefd7d-3af2-44c8-ae2e-135fefa6205c,0,5560000.0
4,00319825-e81b-4a93-bf9a-eef836ccf6ce,eb77b590-b255-4ea1-b11a-d445a259ac62,af09a9a4-3cc2-4b36-a8d2-e2d06452db5d,a5990fd0-6d85-4273-bb17-d912b688469c,f9eefd7d-3af2-44c8-ae2e-135fefa6205c,0,5560000.0
...,...,...,...,...,...,...,...
8170,ff779270-ee68-46cc-929c-cdd67d328772,eb77b590-b255-4ea1-b11a-d445a259ac61,58524699-d48a-46c8-8c09-48f2dc91695a,1123257d-8bc0-4192-84fc-1bfb71d57d82,a5d628a2-c2bf-48ba-aa55-e892bc7f3e4a,1,4140000.0
8171,ff779270-ee68-46cc-929c-cdd67d328772,eb77b590-b255-4ea1-b11a-d445a259ac61,58524699-d48a-46c8-8c09-48f2dc91695a,a5990fd0-6d85-4273-bb17-d912b688469c,a5d628a2-c2bf-48ba-aa55-e892bc7f3e4a,1,4140000.0
8172,ff779270-ee68-46cc-929c-cdd67d328772,eb77b590-b255-4ea1-b11a-d445a259ac61,35ecf9bf-a768-4f56-b954-971dd9b267d6,a5990fd0-6d85-4273-bb17-d912b688469c,a5d628a2-c2bf-48ba-aa55-e892bc7f3e4a,0,4140000.0
8173,ff779270-ee68-46cc-929c-cdd67d328772,eb77b590-b255-4ea1-b11a-d445a259ac61,6be3c699-8ee2-4d8a-9b09-ace459775213,a5990fd0-6d85-4273-bb17-d912b688469c,a5d628a2-c2bf-48ba-aa55-e892bc7f3e4a,0,4140000.0
8174,ff779270-ee68-46cc-929c-cdd67d328772,eb77b590-b255-4ea1-b11a-d445a259ac61,35ecf9bf-a768-4f56-b954-971dd9b267d6,1123257d-8bc0-4192-84fc-1bfb71d57d82,a5d628a2-c2bf-48ba-aa55-e892bc7f3e4a,0,4140000.0

#### 5.8 Cek duplikasi dan Missing Value

In [58]:
# Cek missing values
missing_values = df_destination_fact.isnull().sum()
print("Jumlah Missing Values:\n", missing_values)

# Cek duplikasi data
duplicate_rows = df_destination_fact.duplicated().sum()
print("Jumlah Duplikasi Data:", duplicate_rows)

Jumlah Missing Values:
 destinations_id        0
categories_id          0
medias_id              0
facilities_id          0
address_id             0
total_content_video    0
total_pendapatan       0
dtype: int64
Jumlah Duplikasi Data: 0

### 6. Load to Big Query

#### 6.1 Konfigurasi ke Big Query

In [59]:
# Load environment variables from .env file
load_dotenv()

# Google Cloud configurations
project_id = os.getenv('GOOGLE_CLOUD_PROJECT_ID')
dataset_id = os.getenv('GOOGLE_CLOUD_DATASET_ID')
google_application_credentials = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')

# Set GOOGLE_APPLICATION_CREDENTIALS environment variable
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = google_application_credentials

# Load Google Cloud credentials
credentials = service_account.Credentials.from_service_account_file(google_application_credentials)

#### 6.2 Load dataframe to big query

In [60]:
# Dictionary to map DataFrame names to BigQuery table names
dataframes = {
    'dim_facilities': df_dim_facilities,
    'dim_address': df_dim_address,
    'dim_destinations': df_dim_destinations,
    'dim_categories': df_dim_categories,
    'dim_medias': df_dim_medias,
    'destination_fact': df_destination_fact,
    'admins': df_admins,
}

# Function to load DataFrame into BigQuery
def load_to_bq(df, table_name):
    table_id = f"{project_id}.{dataset_id}.{table_name}"
    to_gbq(df, table_id, project_id=project_id, if_exists='replace', credentials=credentials)

# Iterate over DataFrame dictionary and load each to BigQuery
for table_name, df in dataframes.items():
    load_to_bq(df, table_name)

print("All dataframes loaded to BigQuery successfully.")

100%|██████████| 1/1 [00:00<00:00, 979.29it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<?, ?it/s]

All dataframes loaded to BigQuery successfully.